# Tasks for installing a certificate used for connecting to taskserver
---
- name: Check whether local certificate exists
  local_action:
    module: stat
    path: "{{ item.src }}"
  register: taskwarrior_local_cert

- name: Create configuration directory for taskwarrior
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: 0700
    owner: "{{ taskwarrior_user_id }}"
  when: taskwarrior_local_cert.stat.exists

- name: Install certificate for using the taskserver
  copy:
   src: "{{ item.src }}"
   dest: "{{ item.dest }}"
   mode: 0400
   owner: "{{ taskwarrior_user_id }}"
  when: taskwarrior_local_cert.stat.exists
