# Tasks for installing a certificate which are needed in order to connect
# to a taskserver
---
- name: Create configuration directory for taskwarrior
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: 0o700
    owner: "{{ taskwarrior_user_id }}"
  when: item.src

- name: Install certificate for using the taskserver
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0o400
    owner: "{{ taskwarrior_user_id }}"
  when: item.src
