---
- tags: [taskwarrior]
  block:
    - name: Install taskwarrior
      package: name={{ item }} state=present
      with_items:
        - taskwarrior
        - tasksh

    - name: Discover home directory of taskwarrior user
      getent:
        database: passwd
        key: "{{ taskwarrior_user_id }}"
        split:

    - name: Read XDG_CONFIG_HOME of taskwarrior user
      shell: echo $XDG_CONFIG_HOME
      become: yes
      become_user: "{{ taskwarrior_user_id }}"
      register: taskwarrior_xdg_config_home_shell

    - name: Configure taskwarrior
      template:
        src: taskrc
        dest: "{{ taskwarrior_user_dir }}/.taskrc"
        mode: 0600
        owner: "{{ taskwarrior_user_id }}"
