---
- tags: [taskwarrior]
  block:
    - name: Install taskwarrior
      package: name={{ item }} state=present
      with_items:
        - taskwarrior
        - tasksh

    - name: Gather facts about the user for whom taskwarrior shall be configured
      getent:
        database: passwd
        key: "{{ taskwarrior_user_id }}"
        split:

    - name: Configure taskwarrior
      template:
        src: taskrc
        dest: "{{ taskwarrior_user_dir }}/.taskrc"
        mode: 0600
        owner: "{{ taskwarrior_user_id }}"
