---
- tags: [taskwarrior]
  block:
    - name: Install taskwarrior
      package: name={{ item }} state=present
      with_items:
        - taskwarrior
        - tasksh

    - name: Discover home directory of taskwarrior user
      getent:
        database: passwd
        key: "{{ taskwarrior_user_id }}"
        split:

    - name: Configure taskwarrior
      template:
        src: taskrc
        dest: "{{ taskwarrior_user_dir }}/.taskrc"
        mode: 0600
        owner: "{{ taskwarrior_user_id }}"

    - name: Install certificates for using the taskserver
      include: install_cert.yml
      loop:
        - src: "{{ taskwarrior_server_certificate }}"
          dest: "{{ taskwarrior_server_certificate_dest }}"
        - src: "{{ taskwarrior_client_certificate }}"
          dest: "{{ taskwarrior_client_certificate_dest }}"
        - src: "{{ taskwarrior_client_key }}"
          dest: "{{ taskwarrior_client_key_dest }}"

    - name: Install cron job for syncing taskwarrior
      cron:
        name: sync taskwarrior
        job: task sync
        user: "{{ taskwarrior_user_id }}"
        special_time: hourly
      when: taskwarrior_cronjob_sync
